### ISSUE TITLE
Tomb Raider 2,3 wrong paths

### ISSUE THREAD

**Issue by jeukel** [petchema/playonlinux#11]
When it cd is ask for its path, it checks for the direction ./ as it was a script for it never gets it. If mount point is called 'TR2' then it will looks for file 'TR2/./setup.exe' .

Thanks.

**Comment by petchema** [comment]
I don't maintain tomb raider scripts, i have no idea why you're writing this here

**Comment by petchema** [comment]
Ah, wip directory. If something breaks in there, you can keep the pieces
